export type CoreBoundaryErrorCode =
  | "cas-budget-exceeded"
  | "cas-cleanup-conflict"
  | "cas-commit-failed"
  | "cas-postcondition-failed"
  | "cas-precondition-failed"
  | "cas-stage-failed"
  | "cas-state-invalid"
  | "filesystem-operation-failed"
  | "invalid-cas-request"
  | "invalid-evidence-artifact-store-request"
  | "invalid-process-executable"
  | "invalid-process-containment-request"
  | "invalid-process-request"
  | "invalid-permission-broker-options"
  | "invalid-permission-request"
  | "invalid-project-initialization-plan-request"
  | "invalid-project-root"
  | "invalid-project-state-request"
  | "invalid-project-path-options"
  | "invalid-project-root-listing-request"
  | "invalid-run-receipt-store-request"
  | "invalid-workflow-checkpoint-request"
  | "invalid-workflow-checkpoint-store-request"
  | "project-path-budget-exceeded"
  | "project-path-case-conflict"
  | "project-path-escape"
  | "project-path-exists"
  | "project-path-link"
  | "project-path-not-found"
  | "project-path-type-mismatch"
  | "project-root-drift"
  | "project-root-entry-unrepresentable"
  | "project-root-listing-budget-exceeded"
  | "project-root-not-directory"
  | "project-root-not-found"
  | "project-state-initialization-failed"
  | "project-state-initialization-uncertain"
  | "evidence-artifact-budget-exceeded"
  | "evidence-artifact-conflict"
  | "evidence-artifact-corrupt"
  | "evidence-artifact-mismatch"
  | "evidence-artifact-source-invalid"
  | "evidence-artifact-store-not-found"
  | "evidence-artifact-write-failed"
  | "run-receipt-store-artifact-invalid"
  | "run-receipt-store-budget-exceeded"
  | "run-receipt-store-conflict"
  | "run-receipt-store-corrupt"
  | "run-receipt-store-mismatch"
  | "run-receipt-store-not-found"
  | "run-receipt-store-receipt-invalid"
  | "run-receipt-store-redaction-required"
  | "run-receipt-store-write-failed"
  | "process-cancelled-before-spawn"
  | "process-containment-host-unsupported"
  | "process-containment-witness-invalid"
  | "process-executable-budget-exceeded"
  | "process-executable-drift"
  | "process-executable-link"
  | "process-executable-not-file"
  | "process-executable-not-found"
  | "process-timeout-before-spawn"
  | "process-working-directory-drift"
  | "permission-budget-exceeded"
  | "permission-command-not-found"
  | "permission-feature-invalid"
  | "permission-feature-scope-invalid"
  | "permission-grant-ambiguous"
  | "permission-grant-exhausted"
  | "permission-grant-expired"
  | "permission-grant-invalid"
  | "permission-grant-mismatch"
  | "permission-grant-signature-invalid"
  | "permission-input-invalid"
  | "permission-lease-state-invalid"
  | "permission-project-mismatch"
  | "permission-reconciliation-required"
  | "permission-scope-invalid"
  | "permission-stage-unsupported"
  | "permission-workflow-invalid"
  | "invalid-project-lane-request"
  | "project-lane-busy"
  | "project-lane-cancelled"
  | "project-lane-expired"
  | "project-lane-identity-mismatch"
  | "project-lane-lock-invalid"
  | "project-lane-lock-write-failed"
  | "project-lane-ownership-lost"
  | "project-lane-recovery-failed"
  | "project-lane-release-failed"
  | "project-lane-state-invalid"
  | "workflow-checkpoint-budget-exceeded"
  | "workflow-checkpoint-plan-mismatch"
  | "workflow-checkpoint-receipt-invalid"
  | "workflow-checkpoint-resume-unsafe"
  | "workflow-checkpoint-state-invalid"
  | "workflow-checkpoint-store-conflict"
  | "workflow-checkpoint-store-corrupt"
  | "workflow-checkpoint-store-mismatch"
  | "workflow-checkpoint-store-not-found"
  | "workflow-checkpoint-store-write-failed"
  | "workflow-checkpoint-transition-invalid"
  | "unsafe-project-root";

export class CoreBoundaryError extends Error {
  readonly code: CoreBoundaryErrorCode;
  readonly path: string;
  readonly mutationUncertain: boolean;

  constructor(
    code: CoreBoundaryErrorCode,
    path: string,
    message: string,
    mutationUncertain = false,
  ) {
    super(`${path}: ${message}`);
    this.name = "CoreBoundaryError";
    this.code = code;
    this.path = path;
    this.mutationUncertain = mutationUncertain;
  }
}
